name: CD - Deploy Application

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::243772031845:role/ai-cloud-github-actions-role
          aws-region: ap-south-1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/arm64 \
            -t ai-assisted-cloud-deployment:latest \
            --load .

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin \
          243772031845.dkr.ecr.ap-south-1.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag ai-assisted-cloud-deployment:latest \
          243772031845.dkr.ecr.ap-south-1.amazonaws.com/ai-assisted-cloud-deployment:latest

      - name: Push Docker image to ECR
        run: |
          docker push \
          243772031845.dkr.ecr.ap-south-1.amazonaws.com/ai-assisted-cloud-deployment:latest

      - name: Deploy to EC2
        run: |
          aws ssm send-command \
            --region ap-south-1 \
            --instance-ids i-06e4612f00a73faf3 \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "sudo docker login --username AWS --password-stdin 243772031845.dkr.ecr.ap-south-1.amazonaws.com <<< $(aws ecr get-login-password --region ap-south-1)",
              "sudo docker pull 243772031845.dkr.ecr.ap-south-1.amazonaws.com/ai-assisted-cloud-deployment:latest",
              "sudo docker stop ai-cloud-app || true",
              "sudo docker rm ai-cloud-app || true",
              "sudo docker run -d -p 5000:5000 --name ai-cloud-app 243772031845.dkr.ecr.ap-south-1.amazonaws.com/ai-assisted-cloud-deployment:latest"
            ]'